"""
Unit tests for the Optimizer class in fsrs.optimizer.

The tests cover:
- Behavior with zero review logs (should return default parameters) 
- Behavior with a sample set of review logs (parameters should change and loss should improve)
- Behavior with fewer than the minimum number of review logs (should return default parameters)
- Invariance to the order of review logs
- Handling of cards with difficulty driven down to 1.0
- Performance with the minimum number of review logs (512)
- Test that optimized parameters lie within specified bounds
- Validity of computed probabilities and costs
- Correct counting of reviews for optimization
- Acceptance of tuple review logs
- String representation of the optimizer
- Performance of optimization under 10k reviews
- Generalization and overfitting checks with a train/val/test split
- Evaluation of AUC-ROC and ECE metrics for the optimized model

Run this test file:
    docker compose exec backend pytest src/tests/test_fsrs_optimizer.py -v
"""

from services.fsrs.optimizer import Optimizer, max_seq_len
from services.fsrs.scheduler import Scheduler, DEFAULT_PARAMETERS, LOWER_BOUNDS_PARAMETERS, UPPER_BOUNDS_PARAMETERS
from services.fsrs.card import Card
from services.fsrs.review_log import ReviewLog
from services.fsrs.grade import Grade

import time
import torch
import pandas as pd
from copy import deepcopy
from random import shuffle
import numpy as np
import pytest
from datetime import datetime, timezone, timedelta
from sklearn.metrics import roc_auc_score


test_optimal_parameters = [
    0.12340357383516173,
    1.2931,
    2.397673571899466,
    8.2956,
    6.686820427099132,
    0.45021679958387956,
    3.077875127553957,
    0.053520395733247045,
    1.6539992229052127,
    0.1466206769107436,
    0.6300772488850335,
    1.611965002575047,
    0.012840136810798864,
    0.34853762746216305,
    1.8878958285806287,
    0.8546376191171063,
    1.8729,
    0.6748536823468675,
    0.20451266082721842,
    0.22622814695113844,
    0.46030603398979064,
]


def get_revlogs() -> list[ReviewLog]:
    """
    reads a csv of prepared exported anki review logs
    and returns them as a list of ReviewLog objects
    """

    df = pd.read_csv("src/tests/sample_data/sample_logs.csv")

    review_logs = []
    for index, row in df.iterrows():
        card_id = row["card_id"]
        grade = Grade(row["grade"])
        review_datetime = datetime.fromisoformat(row["review_datetime"])
        review_duration = row["review_duration"]

        review_log = ReviewLog(
            card_id=str(card_id),
            grade=grade,
            review_datetime=review_datetime,
            review_duration=review_duration,
        )

        review_logs.append(review_log)

    return review_logs


def get_large_revlogs() -> list[ReviewLog]:
    """
    Reads a larger synthetic CSV of review logs (5,000 cards, ~89k reviews)
    generated by src/tests/sample_data/generate_large_sample_logs.py.

    Used for split-based tests where the 10% val/test slices need enough reviews
    to produce statistically stable BCELoss values.
    """
    df = pd.read_csv("src/tests/sample_data/large_sample_logs.csv")

    review_logs = []
    for _, row in df.iterrows():
        review_log = ReviewLog(
            card_id=str(row["card_id"]),
            grade=Grade(row["grade"]),
            review_datetime=datetime.fromisoformat(row["review_datetime"]),
            review_duration=row["review_duration"],
        )
        review_logs.append(review_log)

    return review_logs

def get_min_logs_for_optimization(review_logs):
    for i in range(1, len(review_logs) + 1):
        subset = review_logs[:i]
        optimizer = Optimizer(review_logs=subset)
        if optimizer._num_reviews() >= 512:
            return subset
    return None

def collect_predictions(
        parameters: list[float], review_logs: list[ReviewLog]
    ) -> tuple[list[float], list[int]]:
        """
        Helper: replay each card's review history with the given parameters and
        collect (y_pred, y_true) pairs for all delayed (non-same-day) reviews.
        """
        scheduler = Scheduler(parameters=parameters)
        optimizer_tmp = Optimizer(review_logs=review_logs)
        revlogs_dict = optimizer_tmp._revlogs_train

        y_preds: list[float] = []
        y_trues: list[int] = []

        for card_id, card_review_history in revlogs_dict.items():
            for i, review in enumerate(card_review_history[:max_seq_len]):
                x_date = review[0][0]
                u_grade = review[0][1]
                y_true = review[1]

                if i == 0:
                    card = Card(card_id=card_id, due=x_date)

                if card.last_review and (x_date - card.last_review).days > 0:
                    y_pred = scheduler.get_card_retrievability(
                        card=card, current_datetime=x_date
                    )
                    if isinstance(y_pred, torch.Tensor):
                        y_pred = y_pred.item()
                    y_preds.append(float(y_pred))
                    y_trues.append(int(y_true))

                card, _ = scheduler.review_card(
                    card=card, grade=u_grade, review_datetime=x_date, review_duration=None
                )

        return y_preds, y_trues

class TestOptimizer:
    def test_zero_revlogs(self):
        """
        if no review logs are provided, the optimal parameters should not change
        from the starting parameters
        """

        review_logs = []

        optimizer = Optimizer(review_logs=review_logs)

        optimal_parameters = optimizer.compute_optimal_parameters()

        assert optimal_parameters == list(DEFAULT_PARAMETERS)

    def test_review_logs(self):
        """
        test the optimizer on a set of exported anki review logs
        """

        review_logs = get_revlogs()

        optimizer = Optimizer(review_logs=review_logs)

        optimal_parameters = optimizer.compute_optimal_parameters()

        # the optimal paramaters are no longer equal to the starting parameters
        assert optimal_parameters != list(DEFAULT_PARAMETERS)

        # the output is expected and deterministic
        assert np.allclose(optimal_parameters, test_optimal_parameters)

        # the computed loss with the optimized parameters are less than that of the starting parameters
        starting_loss = optimizer._compute_batch_loss(parameters=DEFAULT_PARAMETERS)
        optimized_loss = optimizer._compute_batch_loss(parameters=optimal_parameters)
        assert optimized_loss < starting_loss

        # calling the same optimizer again will yield the same parameters
        optimal_parameters_again = optimizer.compute_optimal_parameters()
        assert optimal_parameters == optimal_parameters_again

        # initializing another optimizer will give the same results as the original optimizer
        optimizer_new = Optimizer(review_logs=review_logs)
        optimal_parameters_new = optimizer_new.compute_optimal_parameters()
        assert optimal_parameters == optimal_parameters_new

    def test_few_review_logs(self):
        """
        if very few review logs are provided to the optimizer, return unchanged default parameters
        """

        review_logs = get_revlogs()

        # if there are fewer review logs than the minibatch size of 512, then the parameters returned are the starting parameters
        few_revlogs = review_logs[0:500]

        optimizer = Optimizer(review_logs=few_revlogs)

        optimal_parameters = optimizer.compute_optimal_parameters()

        assert optimal_parameters == list(DEFAULT_PARAMETERS)

    def test_unordered_review_logs(self):
        """
        the order of the ReviewLog objects passed to the Optimizer doesn't matter
        as they're sorted within the object
        """

        review_logs = get_revlogs()

        reviewlogs_copy1 = deepcopy(review_logs)
        reviewlogs_copy2 = deepcopy(review_logs)

        # randomly shuffle the review logs
        shuffle(reviewlogs_copy1)
        shuffle(reviewlogs_copy2)

        optimizer1 = Optimizer(review_logs=reviewlogs_copy1)
        optimizer2 = Optimizer(review_logs=reviewlogs_copy2)

        optimal_parameters1 = optimizer1.compute_optimal_parameters()
        optimal_parameters2 = optimizer2.compute_optimal_parameters()

        assert optimal_parameters1 == optimal_parameters2

    def test_optimize_review_logs_with_difficulty_1_cards(self):
        """
        Create hypothetical review logs where cards have
        their difficulty values driven down to 1.0 after repeated easy grades.
        """

        scheduler = Scheduler()
        review_logs = []
        for _ in range(100):
            card = Card()
            for day in range(100):
                card, review_log = scheduler.review_card(
                    card=card,
                    grade=Grade.Easy,
                    review_datetime=datetime(2022, 11, 29, 12, 30, 0, 0, timezone.utc)
                    + timedelta(days=day),
                )
                review_logs.append(review_log)

            assert card.difficulty == 1.0

        optimizer = Optimizer(review_logs=review_logs)
        _ = optimizer.compute_optimal_parameters()  # this should not raise an exception
    
    def test_optimizer_with_minimum_review_logs(self):
        """
        Test that the optimizer can compute optimal parameters with exactly the minimum number of review logs (512).
        """

        review_logs = get_revlogs()

        # take the first 512 review logs (not including the same day reviews)
        min_review_logs = get_min_logs_for_optimization(review_logs)
        
        optimizer = Optimizer(review_logs=min_review_logs)

        optimal_parameters = optimizer.compute_optimal_parameters()

        # the optimal parameters should be computed and not equal to the default parameters
        assert optimal_parameters != list(DEFAULT_PARAMETERS)

        # Confirm optimization improved loss
        starting_loss = optimizer._compute_batch_loss(parameters=DEFAULT_PARAMETERS)
        optimized_loss = optimizer._compute_batch_loss(parameters=optimal_parameters)

        assert optimized_loss < starting_loss

    def test_parameters_within_bounds_after_optimization(self):
        """
        Every parameter returned by compute_optimal_parameters should lie within
        its respective lower and upper bounds.
        """
        review_logs = get_revlogs()
        optimizer = Optimizer(review_logs=review_logs)
        optimal_parameters = optimizer.compute_optimal_parameters()

        for i, (param, lower, upper) in enumerate(
            zip(optimal_parameters, LOWER_BOUNDS_PARAMETERS, UPPER_BOUNDS_PARAMETERS)
        ):
            assert lower <= param <= upper, (
                f"parameters[{i}] = {param} is out of bounds [{lower}, {upper}]"
            )

    def test_num_reviews_count(self):
        """
        _num_reviews should count only delayed (non-same-day) reviews after
        the first review of each card.
        """
        scheduler = Scheduler(enable_fuzzing=False)
        review_logs = []
        base_date = datetime(2025, 1, 1, 0, 0, 0, 0, timezone.utc)

        # Card 1: day 0, day 1, day 2 → first review doesn't count, days 1 and 2 each count → 2
        card1 = Card()
        card1, log = scheduler.review_card(
            card=card1, grade=Grade.Good, review_datetime=base_date
        )
        review_logs.append(log)
        card1, log = scheduler.review_card(
            card=card1, grade=Grade.Good, review_datetime=base_date + timedelta(days=1)
        )
        review_logs.append(log)
        card1, log = scheduler.review_card(
            card=card1, grade=Grade.Good, review_datetime=base_date + timedelta(days=2)
        )
        review_logs.append(log)

        # Card 2: both reviews on day 0 (same day) → 0 count
        card2 = Card()
        card2, log = scheduler.review_card(
            card=card2, grade=Grade.Good, review_datetime=base_date
        )
        review_logs.append(log)
        card2, log = scheduler.review_card(
            card=card2, grade=Grade.Good, review_datetime=base_date + timedelta(minutes=10)
        )
        review_logs.append(log)

        # Card 3: single review only → 0 count
        card3 = Card()
        card3, log = scheduler.review_card(
            card=card3, grade=Grade.Good, review_datetime=base_date
        )
        review_logs.append(log)

        optimizer = Optimizer(review_logs=review_logs)

        assert optimizer._num_reviews() == 2

    def test_optimizer_accepts_tuple_review_logs(self):
        """
        Optimizer should accept review_logs as a tuple and produce the same
        result as when a list is passed.
        """
        review_logs = get_revlogs()

        optimizer_list = Optimizer(review_logs=list(review_logs))
        optimizer_tuple = Optimizer(review_logs=tuple(review_logs))

        params_list = optimizer_list.compute_optimal_parameters()
        params_tuple = optimizer_tuple.compute_optimal_parameters()

        assert params_list == params_tuple

    def test_optimizer_str(self):
        """
        str(optimizer) and repr(optimizer) should return the same value.
        """
        review_logs = get_revlogs()
        optimizer = Optimizer(review_logs=review_logs)

        assert str(optimizer) == repr(optimizer)

    def test_performance_optimization_under_10k_reviews(self):
        """
        compute_optimal_parameters on a review log with fewer than 10,000 valid
        (non-same-day) review events should complete in under 40 seconds.
        """
        review_logs = get_revlogs()

        optimizer = Optimizer(review_logs=review_logs)

        assert optimizer._num_reviews() < 10_000, (
            "Sample data already exceeds 10k reviews — adjust the test dataset."
        )

        start = time.perf_counter()
        optimizer.compute_optimal_parameters()
        elapsed_s = time.perf_counter() - start

        assert elapsed_s < 40.0, (
            f"Optimization took {elapsed_s:.3f}s on <10k reviews, expected < 40s"
        )

    def test_train_val_test_split_no_overfitting(self):
        """
        Split the review logs by card into an 80/10/10 train/val/test split.

        Uses the large synthetic dataset (5,000 cards, ~89k reviews) so that
        each 10% slice has ~500 cards and ~9k reviews — enough for stable
        BCELoss estimates.

        After optimizing on the training set:
        1. BCELoss on the validation set should be lower with the optimized
           parameters than with the default parameters —> confirming the model
           generalises beyond the training data.
        2. The training loss and validation loss should be close to each other
           (within 0.05) —> a large gap would indicate overfitting to the
           training set.
        3. The validation loss and test loss should be close to each other
           (within 0.05) —> confirming the model performs consistently across
           different unseen subsets.
        """
        review_logs = get_large_revlogs()

        # group review logs by card_id
        card_log_map: dict[str, list[ReviewLog]] = {}
        for log in review_logs:
            card_log_map.setdefault(log.card_id, []).append(log)

        card_ids = sorted(card_log_map.keys())
        n = len(card_ids)
        n_train = int(n * 0.8)
        n_val = int(n * 0.1)

        train_ids = set(card_ids[:n_train])
        val_ids = set(card_ids[n_train : n_train + n_val])
        test_ids = set(card_ids[n_train + n_val :])

        train_logs = [log for log in review_logs if log.card_id in train_ids]
        val_logs = [log for log in review_logs if log.card_id in val_ids]
        test_logs = [log for log in review_logs if log.card_id in test_ids]

        # optimise on training split
        train_optimizer = Optimizer(review_logs=train_logs)
        optimized_params = train_optimizer.compute_optimal_parameters()

        # evaluate BCELoss on all three splits
        train_loss_optimized = train_optimizer._compute_batch_loss(parameters=optimized_params)

        val_optimizer = Optimizer(review_logs=val_logs)
        val_loss_default = val_optimizer._compute_batch_loss(parameters=DEFAULT_PARAMETERS)
        val_loss_optimized = val_optimizer._compute_batch_loss(parameters=optimized_params)

        test_optimizer = Optimizer(review_logs=test_logs)
        test_loss_optimized = test_optimizer._compute_batch_loss(parameters=optimized_params)

        # 1. Generalisation: optimized params lower val loss compared to default
        assert val_loss_optimized < val_loss_default, (
            f"Val BCELoss did not improve: default={val_loss_default:.4f}, "
            f"optimized={val_loss_optimized:.4f}"
        )

        # 2. No overfitting: training and validation losses are close
        assert abs(train_loss_optimized - val_loss_optimized) < 0.05, (
            f"Large gap between train ({train_loss_optimized:.4f}) and val "
            f"({val_loss_optimized:.4f}) losses suggests overfitting"
        )

        # 3. Consistent generalisation: val and test losses are close
        assert abs(val_loss_optimized - test_loss_optimized) < 0.05, (
            f"Large gap between val ({val_loss_optimized:.4f}) and test "
            f"({test_loss_optimized:.4f}) losses — model is inconsistent across unseen splits"
        )

    def test_auc_roc_and_ece_metrics(self):
        """
        Evaluate the optimized model using AUC-ROC and ECE (Expected Calibration Error)
        on the full review log set. AUC-ROC measures how well the model separates remembered vs forgotten cards.
        ECE measures how well the predicted probabilities are calibrated with actual outcomes.

        AUC-ROC > 0.5  — predictions are better than random chance.
        ECE < 0.2      — predicted retrievability probabilities are reasonably calibrated.
        """
        review_logs = get_revlogs()

        optimizer = Optimizer(review_logs=review_logs)
        optimized_params = optimizer.compute_optimal_parameters()

        y_preds, y_trues = collect_predictions(
            parameters=optimized_params, review_logs=review_logs
        )

        assert len(y_preds) > 0, "No prediction pairs were collected."

        y_preds_arr = np.array(y_preds, dtype=np.float64)
        y_trues_arr = np.array(y_trues, dtype=np.int32)

        # --- AUC-ROC (computed with sklearn) ---
        auc_roc = roc_auc_score(y_trues_arr, y_preds_arr)

        assert auc_roc > 0.5, (
            f"AUC-ROC = {auc_roc:.4f}, expected > 0.5 (better than random)"
        )

        # --- ECE (Expected Calibration Error) with 10 equal-width bins ---
        num_bins = 10
        bin_edges = np.linspace(0.0, 1.0, num_bins + 1)
        ece = 0.0
        n_total = len(y_preds_arr)

        for i in range(num_bins):
            lo, hi = bin_edges[i], bin_edges[i + 1]
            # if it's the last bin, include predictions equal to 1.0; otherwise, only include predictions < hi
            if i == num_bins - 1:
                in_bin = (y_preds_arr >= lo) & (y_preds_arr <= hi)
            else:
                in_bin = (y_preds_arr >= lo) & (y_preds_arr < hi)
            
            # check that the bin is not empty
            if in_bin.sum() == 0:
                continue
            bin_confidence = y_preds_arr[in_bin].mean()
            bin_accuracy = y_trues_arr[in_bin].mean()
            ece += (in_bin.sum() / n_total) * abs(bin_confidence - bin_accuracy)

        assert ece < 0.2, (
            f"ECE = {ece:.4f}, expected < 0.2 (reasonably calibrated)"
        )